name: Docker Push Images

on:
  workflow_dispatch:
    
  
jobs:
  
  run_remote:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: delete kubernetes folder
      uses: appleboy/ssh-action@master
      continue-on-error: true
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port:  22 
        script: |         
          rm -rf Kubernetes/

      
    - name: copy kubernetes folder via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        source: "Kubernetes/*"
        target: "/home/${{ secrets.SERVER_USER }}"
      
    # - name: remote ssh delete old k8s manifests
    #   uses: appleboy/ssh-action@master
    #   continue-on-error: true
    #   with:
    #     host: ${{ secrets.SERVER_HOST }}
    #     username: ${{ secrets.SERVER_USER }}
    #     password: ${{ secrets.SERVER_PASSWORD }}
    #     port:  22 
    #     script: |
    #       kubectl delete all --all -n motobook 
    #       kubectl delete ns motobook 
    #       kubectl delete -f Kubernetes/
    #       kubectl delete clusterissuer letsencrypt-staging letsencrypt-production -n istio-system
    #       kubectl delete certificate ingress-cert-staging ingress-cert-production -n istio-system
    #       kubectl delete secret ingress-cert-staging ingress-cert-production -n istio-system

    - name: remote ssh apply k8s manifests
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port:  22 
        script:  kubectl apply -f Kubernetes/namespace/ns.yaml &&
           kubectl apply -f Kubernetes/ && 
          kubectl apply -f Kubernetes/virtual_services/  &&
          kubectl apply -f Kubernetes/authentication_namespace/ &&
          kubectl apply -f Kubernetes/gateway/gateway_no_https.yaml &&
          kubectl apply -f Kubernetes/certificate/ &&
          sleep 5m &&
          kubectl apply -f Kubernetes/gateway/gateway.yaml
